name: CI Pipeline

# Déclencheur du workflow : sur push ou pull request sur la branche 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Utilisation de l'image Ubuntu pour exécuter le job

    steps:
      # 1. Checkout du code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configuration de Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Choisir la version de Python

      # 3. Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installer les dépendances du fichier requirements.txt

      # 4. Exécution des tests unitaires avec pytest
      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings  # Lancer les tests unitaires avec pytest
